linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2
      min_acceleration       : -0.5 # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 0.78 # rad/s
    min_velocity           : -0.78
    has_acceleration_limits: true
    max_acceleration       : 0.78  # rad/s^2
    min_acceleration       : -0.78
