global_frame: odom
#robot_base_link: base_link
rolling_window: true
static_map: false
#update_frequency: 5.0
#publish_frequency: 2.0
width: 3.0
height: 3.0
resolution: 0.05
#meter_scoring: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
