global_frame: odom
#global_frame: /stereo/stereo_odometry
robot_base_link: base_link
rolling_window: true
static_map: false
width: 4.0
height: 4.0
#resolution: 0.1
#always_send_full_costmap: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
